apiVersion: v1
kind: Service
metadata:
  name: treasure-cart-service
spec:
  selector:
    app: treasure-cart
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 7000  
  type: LoadBalancer  